### PR TITLE
Feature: Option to add a signature

### LINKED ISSUE #1: Feature: Option to add a signature
I would like to have the option to add a signature to an invoice between the complementary close and the name.

If you are fine with this feature request, I can also try to make a pull request for this.

Also, thank you for this package :)

### PR DESCRIPTION
**Pull request by ikelax**
Closes #1.

@erictapen Shall I also bump the version and/or adjust the template?

### CODE REVIEW

**Comment by erictapen** [comment]
Thanks, I'll bump the version. Do you happen to have an example signature that we could use in the `main.typ`?

**Comment by ikelax** [comment]
Unfortunately, I do not have one. However, I just found [this website](https://signaturely.com/online-signature/type/).

**Comment by erictapen** [comment]
I ended up changing the API for defining signatures actually, as I had trouble providing the correct path to the image file.

I personally chose a style that will make the signature a little to big, as if it was written on top of the printout. What do you think?

**Comment by erictapen** [comment]
Release is in progress: https://github.com/typst/packages/pull/986

**Comment by ikelax** [comment]
> I ended up changing the API for defining signatures actually, as I had trouble providing the correct path to the image file.
> 
> I personally chose a style that will make the signature a little to big, as if it was written on top of the printout. What do you think?

It looks fine to me. I will test it this evening and (hopefully remind to) tell you how I like it in practice :)

**Pull request merged**
